// src/services/api.js
import axios from 'axios';

// IMPORTANT: In a real app, this would come from a login process and be stored securely.
// For this POC, we hardcode it. This token will need to be generated by your backend's
// security layer once you implement it. For now, it's just a placeholder.
const HARDCODED_JWT_TOKEN = "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJwb2MtdXNlciIsImlhdCI6MTc1NzE2ODMxNiwiZXhwIjoyNjIxMTY4MzE2fQ.Fc9ULwZaLuYCQBFhMAHeYjpEq_cec3KWnRxFEXWkVxhwWiKF3LNhop-dZURl1a87";

const HARDCODED_JWT_TOKEN_ATLAS = 'eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJwb2MtdXNlciIsImlhdCI6MTc1NzI3MzIxMSwiZXhwIjoyNjIxMjczMjExfQ.nV43HVT4f_XW_d_9bLz6PhG0Flf94UCEUliJliY-Zv3lIyDjcqj5rY_sRd_jkwiF';

// --- Axios Instance for Cultural Archive ---
const culturalArchiveApi = axios.create({
    baseURL: 'http://localhost:8080/api/v1' // Points to the cultural-archive-app
});

// --- Axios Instance for Sports Atlas ---
const sportsAtlasApi = axios.create({
    baseURL: 'http://localhost:8081/api/v1' // Points to the sports-atlas-app
});

// --- Interceptor Function ---
// This function adds the Authorization header to every request for a given Axios instance.
const addAuthInterceptor = (instance) => {
    instance.interceptors.request.use(config => {
        // We can disable security checks by not adding the token if it's a placeholder
        if (HARDCODED_JWT_TOKEN && HARDCODED_JWT_TOKEN !== "placeholder-jwt-token-for-poc") {
            config.headers.Authorization = `Bearer ${HARDCODED_JWT_TOKEN}`;
        }
        return config;
    });
};

const addAuthInterceptorAtlas = (instance) => {
    instance.interceptors.request.use(config => {
        // We can disable security checks by not adding the token if it's a placeholder
        if (HARDCODED_JWT_TOKEN_ATLAS && HARDCODED_JWT_TOKEN_ATLAS !== "placeholder-jwt-token-for-poc") {
            config.headers.Authorization = `Bearer ${HARDCODED_JWT_TOKEN_ATLAS}`;
        }
        return config;
    });
};

// Apply the interceptor to both instances
addAuthInterceptor(culturalArchiveApi);
addAuthInterceptorAtlas(sportsAtlasApi);


// ====================================================================
//                       API FUNCTION EXPORTS
// ====================================================================

// --- Cultural Archive ---

/**
 * Uploads an audio file and its metadata.
 * @param {FormData} formData - The form data containing the file, title, and assetType.
 * @returns {Promise} Axios promise for the request.
 */
export const uploadAudio = (formData) => {
    return culturalArchiveApi.post('/archive/ingest', formData, {
        headers: {
            'Content-Type': 'multipart/form-data'
        }
    });
};

/**
 * Sends a message to the archive's chat agent.
 * @param {string} message - The user's message.
 * @returns {Promise<string>} A promise that resolves to the agent's string response.
 */
export const chatWithArchive = async (message) => {
    const response = await culturalArchiveApi.post('/archive/chat', { message });
    return response.data; // The backend returns a raw string
};


// --- Sports Atlas ---

/**
 * Uploads a CSV file.
 * @param {FormData} formData - The form data containing the CSV file.
 * @returns {Promise} Axios promise for the request.
 */
export const uploadCsv = (formData) => {
    return sportsAtlasApi.post('/atlas/ingest', formData, {
        headers: {
            'Content-Type': 'multipart/form-data'
        }
    });
};

/**
 * Sends a message to the atlas's chat agent.
 * @param {string} message - The user's message.
 * @returns {Promise<string>} A promise that resolves to the agent's string response.
 */
export const chatWithAtlas = async (message) => {
    const response = await sportsAtlasApi.post('/atlas/chat', { message });
    return response.data;
};


/**
 * Fetches all sports facilities from the backend.
 * @returns {Promise<Array>} A promise that resolves to an array of facility objects.
 */
export const getAllFacilities = async () => {
    const response = await sportsAtlasApi.get('/facilities');
    return response.data;
};