spring.application.name=pulsberry

spring.datasource.url=jdbc:postgresql://localhost:5432/atlas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

langchain4j.vertex-ai-gemini.chat-model.enabled=true
langchain4j.vertex-ai-gemini.chat-model.project=foodguard-453108
langchain4j.vertex-ai-gemini.chat-model.location=us-central1
langchain4j.vertex-ai-gemini.chat-model.model-name=gemini-2.0-flash

kairos.vector.provider=QDRANT
kairos.ingestion.watcher.enabled=true
kairos.crawler.enabled=true
