server.port=8080

# Spring Application Configuration
spring.application.name=cultural-archive-app

# Spring Datasource Configuration (PostgreSQL for relational data)
spring.datasource.url=jdbc:postgresql://localhost:5432/kai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# -----------------------------------------------
# KAIROS Platform Configuration
# -----------------------------------------------

# AI Provider (Google Vertex AI)
kairos.ai.vertex.project-id=foodguard-453108
kairos.ai.vertex.location=us-central1
# You can override other AI properties here if needed, e.g.:
kairos.ai.vertex.chat-model-name=gemini-2.0-flash
# kairos.ai.vertex.temperature=0.5

# Vector Store (ChromaDB)
#kairos.vector-store.chroma.base-url=http://localhost:8000
#kairos.vector-store.chroma.default-collection-name=cultural-archive-v1
#kairos.vector-store.chroma.timeout-seconds=60
kairos.vector-store.opensearch.base-url=http://localhost:9200
kairos.vector-store.opensearch.index-name=cultural-archive-v1
kairos.vector-store.opensearch.username=admin
kairos.vector-store.opensearch.password=A28n12l10@
kairos.vector-store.opensearch.timeout-seconds=60

kairos.security.jwt.secret=5acb8d37c81255d8fb4dda567f792b31093751d0a3dc48c2ca3fd6564e650443
# Expiration time in milliseconds (e.g., 24 hours)
kairos.security.jwt.expiration-ms=864000000000

app.cors.allowed-origins=http://localhost:3000

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

kairos.storage.gcs.bucket-name=menu-dm
kairos.storage.gcs.project-id=foodguard-453108

kairos.ai.vertex.transcription-provider=gemini
